# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.ui & .qrc files/dialog_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 379)
        MainWindow.setMinimumSize(QtCore.QSize(400, 379))
        MainWindow.setMaximumSize(QtCore.QSize(400, 379))
        self.MainWidget = QtWidgets.QWidget(MainWindow)
        self.MainWidget.setMinimumSize(QtCore.QSize(400, 379))
        self.MainWidget.setMaximumSize(QtCore.QSize(400, 379))
        self.MainWidget.setObjectName("MainWidget")
        self.welcome_label = QtWidgets.QLabel(self.MainWidget)
        self.welcome_label.setGeometry(QtCore.QRect(82, 16, 224, 34))
        self.welcome_label.setMinimumSize(QtCore.QSize(224, 34))
        self.welcome_label.setMaximumSize(QtCore.QSize(224, 34))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.welcome_picture = QtWidgets.QLabel(self.MainWidget)
        self.welcome_picture.setGeometry(QtCore.QRect(0, 52, 400, 245))
        self.welcome_picture.setMinimumSize(QtCore.QSize(400, 245))
        self.welcome_picture.setMaximumSize(QtCore.QSize(400, 245))
        self.welcome_picture.setStyleSheet("background-image: url(:/newPrefix/ddos_image.png);")
        self.welcome_picture.setText("")
        self.welcome_picture.setObjectName("welcome_picture")
        self.welcome_button = QtWidgets.QPushButton(self.MainWidget)
        self.welcome_button.setGeometry(QtCore.QRect(2, 302, 396, 69))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_button.setFont(font)
        self.welcome_button.setObjectName("welcome_button")
        # MainWindow.setCentralWidget(self.MainWidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.welcome_label.setText(_translate("MainWindow", "Welcome to program"))
        self.welcome_button.setText(_translate("MainWindow", "OK"))
import picture_rc
