# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.ui & .qrc files/error.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_error_window(object):
    def setupUi(self, error_window):
        error_window.setObjectName("error_window")
        error_window.resize(331, 302)
        error_window.setMinimumSize(QtCore.QSize(10, 10))
        error_window.setMaximumSize(QtCore.QSize(331, 302))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        font.setBold(True)
        font.setWeight(75)
        error_window.setFont(font)
        error_window.setStyleSheet("background-color: rgb(104, 201, 205);")
        self.ok_button = QtWidgets.QPushButton(error_window)
        self.ok_button.setGeometry(QtCore.QRect(10, 246, 311, 46))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.ok_button.setFont(font)
        self.ok_button.setStyleSheet("background-color: rgb(89, 172, 175)")
        self.ok_button.setObjectName("ok_button")
        self.check_label = QtWidgets.QLabel(error_window)
        self.check_label.setGeometry(QtCore.QRect(13, 0, 307, 246))
        self.check_label.setAutoFillBackground(False)
        self.check_label.setStyleSheet("image: url(:/newPrefix/design_for_error_window.png)")
        self.check_label.setText("")
        self.check_label.setAlignment(QtCore.Qt.AlignJustify | QtCore.Qt.AlignVCenter)
        self.check_label.setObjectName("check_label")

        self.retranslateUi(error_window)
        QtCore.QMetaObject.connectSlotsByName(error_window)

    def retranslateUi(self, error_window):
        _translate = QtCore.QCoreApplication.translate
        error_window.setWindowTitle(_translate("error_window", "Error"))
        self.ok_button.setText(_translate("error_window", "OK"))
