# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.ui & .qrc files/dialog_design.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PySide2 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 373)
        Dialog.setMinimumSize(QtCore.QSize(400, 373))
        Dialog.setMaximumSize(QtCore.QSize(400, 373))
        self.welcome_label = QtWidgets.QLabel(Dialog)
        self.welcome_label.setGeometry(QtCore.QRect(82, 16, 224, 34))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(18)
        self.welcome_label.setFont(font)
        self.welcome_label.setObjectName("welcome_label")
        self.welcome_button = QtWidgets.QPushButton(Dialog)
        self.welcome_button.setGeometry(QtCore.QRect(2, 302, 396, 69))
        font = QtGui.QFont()
        font.setFamily("Cambria")
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.welcome_button.setFont(font)
        self.welcome_button.setObjectName("welcome_button")
        self.welcome_picture = QtWidgets.QLabel(Dialog)
        self.welcome_picture.setGeometry(QtCore.QRect(0, 52, 400, 245))
        self.welcome_picture.setStyleSheet("background-image: url(:/newPrefix/ddos_image.png);")
        self.welcome_picture.setText("")
        self.welcome_picture.setObjectName("welcome_picture")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.welcome_label.setText(_translate("Dialog", "Welcome to program"))
        self.welcome_button.setText(_translate("Dialog", "OK"))
import picture_rc
